### ISSUE TITLE
Windows users cannot clone

### ISSUE THREAD

**Issue by shreybohra** [icl-rocketry/art-designs#1]
Windows isn't happy with colons in filenames, https://github.com/icl-rocketry/art-designs/tree/main/Old%20Files/10:10:2021%20zipped causes errors when cloning

git preserves history so old files can be deleted or just rename the dir, either works

**Comment by NathanaelJ** [comment]
Renamed this directory

**Comment by shreybohra** [comment]
https://github.com/icl-rocketry/art-designs/tree/main/Old%20Files/APEX%20%7C%20Mass%20Optimisation

this is also not allowed lol, surprised mac lets you use pipe in a filename

**Comment by NathanaelJ** [comment]
Renamed this one too... I've gotten too comfortable with MacOS filename rules

Tbh, surprised Windows limits your filenames so much - I could use emojis in mine if I wanted to.

**Comment by NathanaelJ** [comment]
Re-open this issue if you spot any more filenames that don't work, but I think we've found them all now...

**Comment by shreybohra** [comment]
jinxed it

https://github.com/icl-rocketry/art-designs/blob/main/Old%20Files/APEX_04:21.ork

**Comment by NathanaelJ** [comment]
Oh dear! Third time's the charm...
